org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.76
neo_version_range=[21.1.0,)
loader_version_range=[4,)

jei_version=19.21.0.247
geckolib_version=4.7

mod_id=avaliproject
mod_name=The Galaxy Comes Alive
mod_license=MIT
mod_version=1.3.1
mod_display_url="https://discord.gg/BcKmBkQeEw"
mod_logo_file="assets/avaliproject/textures/gui/logo.png"
mod_group_id=com.lunkoashtail.avaliproject
mod_authors=LunkoAshtail
mod_description="Mod aimed to add content over multiple races, from avali to protogens, sergals and more..!"
